// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "audioFinder",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "audioFinder",
            targets: ["AppModule"],
            bundleIdentifier: "xd.audioFinder",
            teamIdentifier: "N4LZU5RSN8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .binoculars),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "The microphone will be used to record audio in which a word or phrase can be searched."),
                .speechRecognition(purposeString: "Speech recognition will be used to find a word or phrase in the recorded audio file.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)